version: '3.7'
services:
    php8-sf6:
        container_name: php8-sf6
        build: php8-sf6
        ports:
            - "9000:8000"
        volumes:
            - ./project:/var/www/html

    database:
        image: 'mysql:5.7'
        restart: always
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - "3306"
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        depends_on:
            - database
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: database


volumes:
  db-data:

